services:
  - type: web
    name: road-accident-predictor
    env: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free